// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LiftPos.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LiftPos::LiftPos(double pos, double rate): Command() {
    m_pos = pos;
    m_rate = rate;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lift.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	sloped = false;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void LiftPos::Initialize() {
	Robot::lift->SetSlope(m_rate);
}

// Called repeatedly when this Command is scheduled to run
void LiftPos::Execute() {
	if(!sloped && (TimeSinceInitialized() > 1.0 || (TimeSinceInitialized() > 0.2 && Robot::lift->GetPosError() < 0.3)))
			Robot::lift->SetSlope(0);
	Robot::lift->GotoPos(m_pos);
}

// Make this return true when this Command no longer needs to run execute()
bool LiftPos::IsFinished() {
	if(TimeSinceInitialized() < 0.2)
		return false;
    return Robot::lift->GetInPosition() || Robot::lift->GetVel()<1;
}

// Called once after isFinished returns true
void LiftPos::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LiftPos::Interrupted() {

}
