// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> chassisFrontLeft;
	static std::shared_ptr<CANTalon> chassisFrontRight;
	static std::shared_ptr<CANTalon> chassisRearLeft;
	static std::shared_ptr<CANTalon> chassisRearRight;
	static std::shared_ptr<RobotDrive> chassisRobotDrive41;
	static std::shared_ptr<AnalogInput> chassisRangeFront;
	static std::shared_ptr<AnalogInput> chassisRangeLeft;
	static std::shared_ptr<AnalogInput> chassisRangeRight;
	static std::shared_ptr<CANTalon> intakeArmMotor;
	static std::shared_ptr<CANTalon> rollersMotor;
	static std::shared_ptr<CANTalon> liftCIM1;
	static std::shared_ptr<CANTalon> liftCIM2;
	static std::shared_ptr<Servo> liftShifter;
	static std::shared_ptr<Servo> liftLock;
	static std::shared_ptr<CANTalon> liftPusher;
	static std::shared_ptr<Servo> liftAngleAngle;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
